config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :agents
  resources :properties

  namespace :api do
    namespace :v1 do
      resources :properties
    end
  end
end

app/models/agent.rb
# frozen_string_literal: true

class Agent < ApplicationRecord
  has_many :properties, dependent: :nullify

  validates :first_name, :last_name, :email, presence: true, length: { maximum: 255 }
  validates :email, uniqueness: true

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/models/agent_assigner.rb
# frozen_string_literal: true

class AgentAssigner
  include Wisper::Publisher

  def property_created_with_agent(_property_id)
    # TODO: - This method will email the agent
  end

  def property_created_without_agent(property_id)
    property(property_id)
    assign_agent!
    publish(:property_created_with_agent, property_id)
  end

  def property_updated_with_agent(_property_id)
    # TODO: - This method will email the agent
  end

  def property_updated_without_agent(property_id)
    property(property_id)
    assign_agent!
    publish(:property_updated_with_agent, property_id)
  end

  private

  def property(id)
    @property ||= Property.find(id)
  end

  def assign_agent!
    @property.agent_id = available_agents.sample

    raise 'No Agent in database, cannot assign to Property' if @property.agent_id.blank?

    @property.save!
  end

  def available_agents
    Rails.cache.fetch('agents/all/ids', expires_in: 1.hour) do
      Agent.pluck(:id)
    end
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/property.rb
# frozen_string_literal: true

class Property < ApplicationRecord
  enum status: {
    available: 'available',
    sold: 'sold'
  }

  belongs_to :agent, optional: true

  validates :location, presence: true
  validates :name, presence: true, length: { maximum: 255 }
  validates :price, presence: true
  validates :status, presence: true

  delegate :full_name, to: :agent, prefix: true, allow_nil: true
end

app/models/property_manager.rb
# frozen_string_literal: true

class PropertyManager
  include Wisper::Publisher

  attr_accessor :property, :success

  def initialize(params:, property: nil)
    @params = params
    @property = property
    @success = false
  end

  def create
    @property = Property.new(@params)

    @success = @property.save
    broadcast_create if @success
    self
  end

  def update
    unless @property.is_a? Property
      raise ArgumentError,
            'Property should be an instance of Property'
    end

    @success = @property.update(@params)
    broadcast_update if @success
    self
  end

  private

  def broadcast_create
    if @property.agent_id.present?
      publish(:property_created_with_agent, property.id)
    else
      publish(:property_created_without_agent, property.id)
    end
  end

  def broadcast_update
    if @property.agent_id.present?
      publish(:property_updated_with_agent, property.id)
    else
      publish(:property_updated_without_agent, property.id)
    end
  end
end

app/controllers/agents_controller.rb
# frozen_string_literal: true

class AgentsController < ApplicationController
  before_action :find_agent, only: %i[show edit update destroy]

  # GET /agents
  def index
    @agents = Agent.all
  end

  # GET /agents/1
  def show; end

  # GET /agents/new
  def new
    @agent = Agent.new
  end

  # GET /agents/1/edit
  def edit; end

  # POST /agents
  def create
    @agent = Agent.new(agent_params)

    if @agent.save
      redirect_to @agent, notice: t('.success')
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /agents/1
  def update
    if @agent.update(agent_params)
      redirect_to @agent, notice: t('.success')
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /agents/1
  def destroy
    @agent.destroy
    redirect_to agents_url, notice: t('.success')
  end

  private

  def find_agent
    @agent = Agent.find(params[:id])
  end

  def agent_params
    params.require(:agent).permit(:email, :first_name, :last_name)
  end
end

app/controllers/api/application_controller.rb
# frozen_string_literal: true

module Api
  class ApplicationController < ActionController::API
    rescue_from ActiveRecord::RecordNotFound, with: :not_found

    private

    def not_found
      render json: { error: 'not-found' }, status: :not_found
    end
  end
end

app/controllers/api/v1/properties_controller.rb
# frozen_string_literal: true

module Api
  module V1
    class PropertiesController < Api::ApplicationController
      before_action :find_property, only: %i[show update destroy]

      # GET /properties
      def index
        @properties = Rails.cache.fetch('api/v1/properties/all', expires_in: 1.hour) do
          Property.all.to_a
        end

        render json: @properties
      end

      # GET /properties/1
      def show
        render json: @property
      end

      # POST /properties
      def create
        manager = PropertyManager.new(params: property_params).create
        @property = manager.property

        if manager.success
          render json: @property, status: :created
        else
          render json: { errors: @property.errors }, status: :unprocessable_entity
        end
      end

      # PATCH/PUT /properties/1
      def update
        manager = PropertyManager.new(params: property_params, property: @property).update
        @property = manager.property
        if manager.success
          render json: @property
        else
          render json: { errors: @property.errors }, status: :unprocessable_entity
        end
      end

      # DELETE /properties/1
      def destroy
        @property.destroy!
        head :no_content
      end

      private

      def find_property
        @property = Property.includes(:agent).find(params[:id])
      end

      def property_params
        params.require(:property).permit(:agent_id, :location, :name, :price, :status)
      end
    end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  rescue_from ActiveRecord::RecordNotFound, with: :not_found

  private

  def not_found
    redirect_to properties_url, notice: t('not_found')
  end
end

app/controllers/properties_controller.rb
# frozen_string_literal: true

class PropertiesController < ApplicationController
  before_action :find_property, only: %i[show edit update destroy]

  # GET /properties
  def index
    @properties = Rails.cache.fetch('properties/all', expires_in: 1.hour) do
      Property.includes(:agent).all.to_a
    end
  end

  # GET /properties/1
  def show; end

  # GET /properties/new
  def new
    @property = Property.new
    cached_agents
  end

  # GET /properties/1/edit
  def edit
    cached_agents
  end

  # POST /properties
  def create
    manager = PropertyManager.new(params: property_params).create
    @property = manager.property

    if manager.success
      redirect_to @property, notice: t('.success')
    else
      cached_agents
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /properties/1
  def update
    manager = PropertyManager.new(params: property_params, property: @property).update
    @property = manager.property
    if manager.success
      redirect_to @property, notice: t('.success')
    else
      cached_agents
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /properties/1
  def destroy
    @property.destroy
    redirect_to properties_url, notice: t('.success')
  end

  private

  def find_property
    @property = Property.includes(:agent).find(params[:id])
  end

  def property_params
    params.require(:property).permit(:agent_id, :location, :name, :price, :status)
  end

  def cached_agents
    @agents = Rails.cache.fetch('agents/all/for_select', expires_in: 1.hour) do
      Agent.all.map do |agent|
        [agent.full_name, agent.id]
      end
    end
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/agents/_agent.html.erb
<div id="<%= dom_id agent %>">
  <div>
    First Name
    <p>
      <%= agent.first_name %>
    </p>
  </div>

  <div>
    Last Name

    <p>
      <%= agent.last_name %>
    </p>
  </div>

  <div>
    Email

    <p>
      <%= agent.email %>
    </p>
  </div>
</div>

app/views/agents/_form.html.erb
<%= form_with(model: agent) do |form| %>
  <% if agent.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(agent.errors.count, 'error') %> prohibited this agent from being saved:</h2>

      <ul>
        <% agent.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div>
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div>
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/agents/edit.html.erb
<h1>Editing agent</h1>

<%= render 'form', agent: @agent %>

<br>

<div>
  <%= link_to 'Show this agent', @agent %> |
  <%= link_to 'Back to agents', agents_path %>
</div>

app/views/agents/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Agents</h1>

<div id="agents">
  <table>
    <thead>
      <tr>
        <th>First Name</th>
        <th>Last Name</th>
        <th>Email</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @agents.each do |agent| %>
        <tr>
          <td><%= agent.first_name %></td>
          <td><%= agent.last_name %></td>
          <td><%= agent.email %></td>
          <td><%= link_to 'Show', agent %></td>
          <td><%= link_to 'Edit', edit_agent_path(agent) %></td>
          <td><%= button_to 'Destroy', agent, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<%= link_to 'New agent', new_agent_path %>

app/views/agents/new.html.erb
<h1>New agent</h1>

<%= render 'form', agent: @agent %>

<br>

<div>
  <%= link_to 'Back to agents', agents_path %>
</div>

app/views/agents/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @agent %>

<div>
  <%= link_to 'Edit this agent', edit_agent_path(@agent) %> |
  <%= link_to 'Back to agents', agents_path %>

  <%= button_to 'Destroy this agent', @agent, method: :delete, data: { confirm: 'Are you sure?' }  %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RealState</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/properties/_form.html.erb
<%= form_with(model: property) do |form| %>
  <% if property.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(property.errors.count, 'error') %> prohibited this property from being saved:</h2>

      <ul>
        <% property.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :location %>
    <%= form.text_field :location %>
  </div>

  <div>
    <%= form.label :price %>
    <%= form.number_field :price %>
  </div>

  <div>
    <%= form.label :status %>
    <%= form.select :status, Property.statuses.keys %>
  </div>

  <div>
    <%= form.label :agent_id %>
    <%= form.select :agent_id, @agents, { include_blank: true } %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/properties/_property.html.erb
<div id="<%= dom_id property %>">
  <div>
    Name
    <p>
      <%= property.name %>
    </p>
  </div>

  <div>
    Location

    <p>
      <%= property.location %>
    </p>
  </div>

  <div>
    Price

    <p>
      <%= property.price %>
    </p>
  </div>

  <div>
    Agent

    <p>
      <%= property.agent_full_name %>
    </p>
  </div>
</div>

app/views/properties/edit.html.erb
<h1>Editing property</h1>

<%= render 'form', property: @property %>

<br>

<div>
  <%= link_to 'Show this property', @property %> |
  <%= link_to 'Back to properties', properties_path %>
</div>

app/views/properties/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Properties</h1>

<div id="properties">
  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Location</th>
        <th>Price</th>
        <th>Agent</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @properties.each do |property| %>
        <tr>
          <td><%= property.name %></td>
          <td><%= property.location %></td>
          <td><%= property.price %></td>
          <td><%= property.agent_full_name %></td>
          <td><%= link_to 'Show', property %></td>
          <td><%= link_to 'Edit', edit_property_path(property) %></td>
          <td><%= button_to 'Destroy', property, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<%= link_to 'New property', new_property_path %>

app/views/properties/new.html.erb
<h1>New property</h1>

<%= render 'form', property: @property %>

<br>

<div>
  <%= link_to 'Back to properties', properties_path %>
</div>

app/views/properties/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @property %>

<div>
  <%= link_to 'Edit this property', edit_property_path(@property) %> |
  <%= link_to 'Back to properties', properties_path %>

  <%= button_to 'Destroy this property', @property, method: :delete, data: { confirm: 'Are you sure?' }  %>
</div>